### ISSUE TITLE
DataSection's directory is not cleaned when server restart

### ISSUE THREAD

**Issue by thanhtien522** [rever-tech/fap#4]
Stack trace:
```
org.apache.hadoop.fs.FileAlreadyExistsException: File already exists: data/test_worker-test-2016_12_19_17_00-2016_12_19_17_10/test/2016/11/19/17/test-vunknown-test_worker-2016_12_19_17_00-1.parquet
	at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:264)
	at org.apache.hadoop.fs.RawLocalFileSystem.create(RawLocalFileSystem.java:257)
	at org.apache.hadoop.fs.ChecksumFileSystem$ChecksumFSOutputSummer.<init>(ChecksumFileSystem.java:387)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:449)
	at org.apache.hadoop.fs.ChecksumFileSystem.create(ChecksumFileSystem.java:428)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:908)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:889)
	at org.apache.hadoop.fs.FileSystem.create(FileSystem.java:786)
	at org.apache.parquet.hadoop.ParquetFileWriter.<init>(ParquetFileWriter.java:244)
	at org.apache.parquet.hadoop.ParquetWriter.<init>(ParquetWriter.java:273)
	at org.apache.parquet.hadoop.ParquetWriter$Builder.build(ParquetWriter.java:494)
	at worker.hadoop.file.DataSection.createDataFile(DataSection.scala:67)
	at worker.hadoop.file.DataSection.write(DataSection.scala:85)
	at worker.hadoop.service.HadoopStringWorker.process(HadoopStringWorker.scala:187)
	at worker.hadoop.service.HadoopStringWorker.process(HadoopStringWorker.scala:28)
	at worker.hadoop.service.AbstractKafkaWorker$$anonfun$start$1.apply(Worker.scala:74)
	at worker.hadoop.service.AbstractKafkaWorker$$anonfun$start$1.apply(Worker.scala:74)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at worker.hadoop.service.AbstractKafkaWorker.start(Worker.scala:73)
	at worker.hadoop.Server.delayedEndpoint$worker$hadoop$Server$1(Server.scala:16)
	at worker.hadoop.Server$delayedInit$body.apply(Server.scala:13)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at worker.hadoop.Server.main(Server.scala:13)
```

**Comment by thanhtien522** [comment]
It actually is a bug in Time Based File Naming Strategy
isSectionEnd return not correct value

**Comment by thanhtien522** [comment]
### This issue also lead to a case that may cause failure
DataSection may be created with same name with an existed DataSection in some case:
 - When service restarted, old section is closed and still stored in disk, a new section created with the same name and directory
 - ... (need to be reviewed)
