### ISSUE TITLE
Service interrupted when get schema from Schema Manager fail

### ISSUE THREAD

**Issue by thanhtien522** [rever-tech/fap#5]
Schema is cached in memory, so this case happen when a new schema come.
 When get new schema fail, it should act like this schema not found and the record can be recovered later.

TimeoutException when get schema
```
com.twitter.util.TimeoutException: 5.seconds
	at com.twitter.util.Promise.ready(Promise.scala:663)
	at com.twitter.util.Promise.result(Promise.scala:668)
	at com.twitter.util.Await$$anonfun$result$1.apply(Awaitable.scala:151)
	at com.twitter.concurrent.LocalScheduler$Activation.blocking(Scheduler.scala:214)
	at com.twitter.concurrent.LocalScheduler.blocking(Scheduler.scala:252)
	at com.twitter.concurrent.Scheduler$.blocking(Scheduler.scala:114)
	at com.twitter.util.Await$.result(Awaitable.scala:151)
	at worker.hadoop.service.SchemaManagerService.getSchema(SchemaManagerService.scala:25)
	at worker.hadoop.service.HadoopStringWorker.process(HadoopStringWorker.scala:174)
	at worker.hadoop.service.HadoopStringWorker.process(HadoopStringWorker.scala:28)
```

**Comment by thanhtien522** [comment]
Bug in retryOrNone function is fixed in commit 4503aaa75302ba1a9cb2d375ff76d5915b23e70b
